# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
  
#  1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even-valued terms.

source("functions.R")

fib <- function(n){
  if(n <= 2) {
    return(n)
  }
  else {
    fib(n-1) + fib(n-2)
  }
}

index <- 1
condition <- TRUE
sum_total <- 0

while(condition){
  term <- fib(index)
  if(term > 4*10^6) {
    condition <- FALSE
  }
  else{
    index <- index + 1
    if(is_even(term)){
      sum_total <- sum_total + term
    }
  }
}

print(sum_total)