# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#   
#   1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# 
# Let us list the factors of the first seven triangle numbers:
#   
# 1: 1
# 3: 1,3
# 6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
#
# We can see that 28 is the first triangle number to have over five divisors.
# 
# What is the value of the first triangle number to have over five hundred divisors?

library(numbers)

# This function is slow
num_of_divisors <- function(n) {
  length(which((n / 1:(n/2)) %% 1 == 0)) + 1
}

# This function uses the divisors function from the numbers library
count_divisors <- function(n) {
  length(divisors(n))
}

# Finds the first triangle number with x divisors
triangle_number <- function(x) {
  n <- 0 # term in sequence
  t <- 0 # nth triangle number
  d <- 0 # number of divisors
  while (d < x) {
    n <- n + 1
    t <- t + n
    d <- count_divisors(t)
  }
  return(t)
}

triangle_number(500)